# Generated by Django 5.2.8 on 2025-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Názov firmy, SZCO alebo organizácie",
                        max_length=200,
                        verbose_name="Názov organizácie",
                    ),
                ),
                (
                    "organization_type",
                    models.CharField(
                        choices=[("client", "Klient"), ("partner", "Partner")],
                        default="client",
                        help_text="Client (platí za služby) alebo Partner (poskytuje služby)",
                        max_length=20,
                        verbose_name="Typ organizácie",
                    ),
                ),
                (
                    "ico",
                    models.CharField(
                        blank=True,
                        help_text="Identifikačné číslo organizácie",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="IČO",
                    ),
                ),
                (
                    "dic",
                    models.CharField(
                        blank=True,
                        help_text="Daňové identifikačné číslo",
                        max_length=20,
                        null=True,
                        verbose_name="DIČ",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Úplná adresa organizácie", verbose_name="Adresa"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Hlavný email organizácie",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Hlavné telefónne číslo",
                        max_length=20,
                        null=True,
                        verbose_name="Telefón",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Označuje či je organizácia aktívna v systéme",
                        verbose_name="Aktívna",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvorené"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Aktualizované"),
                ),
            ],
            options={
                "verbose_name": "Organizácia",
                "verbose_name_plural": "Organizácie",
                "ordering": ["-created_at"],
            },
        ),
    ]
