# Generated by Django 5.0.7 on 2025-11-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="ico",
            field=models.CharField(
                blank=True,
                help_text="Identifikačné číslo organizácie",
                max_length=20,
                null=True,
                verbose_name="IČO",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Názov firmy, SZCO alebo organizácie",
                max_length=200,
                null=True,
                verbose_name="Názov organizácie",
            ),
        ),
    ]
