# Generated by Django 5.2.8 on 2025-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Email adresa používateľa (používa sa na prihlásenie)",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
