# Generated by Django 5.0.7 on 2025-11-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrátor"),
                    ("driver", "Vodič"),
                    ("accountant", "Účtovník"),
                    ("user", "Používateľ"),
                ],
                default="user",
                help_text="Rola používateľa v organizácii",
                max_length=20,
                verbose_name="Rola",
            ),
        ),
    ]
