# Generated by Django 5.0.7 on 2025-11-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("manage_organization", "Môže spravovať organizáciu"),
                    (
                        "view_organization_stats",
                        "Môže zobrazovať štatistiky organizácie",
                    ),
                    (
                        "manage_organization_users",
                        "Môže spravovať používateľov organizácie",
                    ),
                    ("manage_vehicles", "Môže spravovať vozidlá"),
                    ("drive_vehicles", "Môže voziť vozidlá"),
                    ("view_vehicle_reports", "Môže zobrazovať výkazy vozidiel"),
                    ("create_trips", "Môže vytvárať jazdy"),
                    ("edit_own_trips", "Môže editovať vlastné jazdy"),
                    ("edit_all_trips", "Môže editovať všetky jazdy"),
                    ("delete_trips", "Môže mazať jazdy"),
                    ("approve_trips", "Môže schvaľovať jazdy"),
                    ("view_reports", "Môže zobrazovať výkazy"),
                    ("generate_reports", "Môže generovať výkazy"),
                    ("export_reports", "Môže exportovať výkazy"),
                    ("manage_accounting", "Môže spravovať účtovníctvo"),
                    ("view_financial_data", "Môže zobrazovať finančné dáta"),
                    ("manage_expenses", "Môže spravovať výdavky"),
                    ("access_admin_panel", "Môže pristupovať k admin panelu"),
                    ("manage_system_settings", "Môže spravovať systémové nastavenia"),
                ],
                "verbose_name": "Používateľ",
                "verbose_name_plural": "Používatelia",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
