# Generated by Django 5.0.7 on 2025-11-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_customuser_options_remove_customuser_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
