import type {
  User,
  Vehicle,
  Driver,
  Trip,
  GpsDevice,
  PartnerSettings,
  AffiliateStats,
  AffiliateReferral,
  AffiliateHistory,
  TripChangeLog,
  Refueling,
  MaintenanceRecord,
  ScheduledMaintenance,
  OdometerReading,
  Place,
  TripTemplate,
  InternalReport,
  ExportTemplate,
  VatReport,
  CompanySettings,
  UserRole,
  Role,
  VehicleDocument,
  Holiday,
  PlannedTrip,
} from "./types"

// Mock Users (with passwords for authentication)
export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: "1",
    email: "admin@knihajazd.sk",
    password: "admin123",
    role: "admin" as Role,
    company: {
      id: "1",
      name: "Demo s.r.o.",
      ico: "12345678",
      dic: "2023456789",
      icdph: "SK2023456789",
      isVatPayer: true,
      address: {
        street: "Hlavná",
        number: "1",
        city: "Bratislava",
        postalCode: "811 01",
        country: "Slovensko",
      },
    },
  },
  {
    id: "2",
    email: "vodic@knihajazd.sk",
    password: "vodic123",
    role: "driver" as Role,
    company: {
      id: "1",
      name: "Demo s.r.o.",
      ico: "12345678",
      dic: "2023456789",
      icdph: "SK2023456789",
      isVatPayer: true,
      address: {
        street: "Hlavná",
        number: "1",
        city: "Bratislava",
        postalCode: "811 01",
        country: "Slovensko",
      },
    },
    driverId: "1",
  },
  {
    id: "3",
    email: "uctovnik@knihajazd.sk",
    password: "uctovnik123",
    role: "accountant" as Role,
    company: {
      id: "1",
      name: "Demo s.r.o.",
      ico: "12345678",
      dic: "2023456789",
      icdph: "SK2023456789",
      isVatPayer: true,
      address: {
        street: "Hlavná",
        number: "1",
        city: "Bratislava",
        postalCode: "811 01",
        country: "Slovensko",
      },
    },
  },
]

// Mock Vehicles
export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "1",
    registrationNo: "BA123CD",
    brand: "Škoda",
    model: "Octavia",
    year: 2020,
    vin: "TMBJJ7NE9L0123456",
    odoInitialKm: 45000,
    ownershipType: "company",
    registrationDate: "2020-03-15",
    vatRegime: "100_business",
    autoImportEnabled: true,
    templateUsageEnabled: true,
    kmMatchingTolerance: 5,
    active: true,
    imageUrl: "/skoda-octavia-silver-2020.jpg",
    fuelConsumption: {
      fuelType: "diesel",
      averageConsumption: 5.8,
      cityConsumption: 6.5,
      highwayConsumption: 5.2,
      combinedConsumption: 5.8,
    },
    insurance: {
      id: "ins-1",
      vehicleId: "1",
      type: "comprehensive",
      policyNumber: "POL-2024-001234",
      insuranceCompany: "Allianz",
      validFrom: "2024-01-01",
      validTo: "2024-12-31",
      reminderDays: 30,
      cost: 850,
      notes: "Poistenie zahŕňa havarijné aj PZP",
    },
  },
  {
    id: "2",
    registrationNo: "BA456EF",
    brand: "VW",
    model: "Passat",
    year: 2019,
    vin: "WVWZZZ3CZKP123456",
    odoInitialKm: 52000,
    ownershipType: "company",
    registrationDate: "2019-07-20",
    vatRegime: "50_mixed",
    autoImportEnabled: true,
    templateUsageEnabled: false,
    kmMatchingTolerance: 3,
    active: true,
    imageUrl: "/vw-passat-blue-2019.jpg",
    fuelConsumption: {
      fuelType: "petrol",
      averageConsumption: 7.2,
      cityConsumption: 8.5,
      highwayConsumption: 6.1,
      combinedConsumption: 7.2,
    },
    insurance: {
      id: "ins-2",
      vehicleId: "2",
      type: "liability",
      policyNumber: "POL-2024-005678",
      insuranceCompany: "Union",
      validFrom: "2024-03-01",
      validTo: "2025-02-28",
      reminderDays: 45,
      cost: 450,
    },
  },
  {
    id: "3",
    registrationNo: "BA789GH",
    brand: "Ford",
    model: "Transit",
    year: 2021,
    vin: "WF0XXXTTFXJX12345",
    odoInitialKm: 28000,
    ownershipType: "private",
    registrationDate: "2021-01-10",
    autoImportEnabled: false,
    templateUsageEnabled: false,
    kmMatchingTolerance: 10,
    active: false,
    fuelConsumption: {
      fuelType: "diesel",
      averageConsumption: 9.5,
      combinedConsumption: 9.5,
    },
  },
]

// Mock Drivers
export const MOCK_DRIVERS: Driver[] = [
  {
    id: "1",
    name: "Peter Novák",
    userId: "2",
    role: "driver",
    defaultVehicleId: "1",
    drivingPermission: "only_default",
  },
  {
    id: "2",
    name: "Ján Kováč",
    userId: "3",
    role: "driver",
    defaultVehicleId: "2",
    drivingPermission: "all_vehicles",
  },
  {
    id: "3",
    name: "Martin Svoboda",
    userId: "4",
    role: "driver",
    drivingPermission: "all_vehicles",
  },
]

// Mock GPS Devices
export const MOCK_GPS_DEVICES: GpsDevice[] = [
  {
    id: "1",
    serialNumber: "GPS001",
    vehicleId: "1",
    isActive: true,
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "2",
    serialNumber: "GPS002",
    vehicleId: "2",
    isActive: true,
    createdAt: "2024-01-02T10:00:00Z",
  },
  {
    id: "3",
    serialNumber: "GPS003",
    isActive: false,
    createdAt: "2024-01-03T10:00:00Z",
  },
]

// Mock Trips
export const MOCK_TRIPS: Trip[] = [
  {
    id: "1",
    vehicleId: "1",
    driverId: "1",
    startLocation: "Bratislava, Hlavná 1",
    endLocation: "Košice, Námestie 5",
    distanceKm: 395,
    startTime: "2024-01-15T08:00:00Z",
    endTime: "2024-01-15T12:30:00Z",
    startOdometer: 45000,
    endOdometer: 45395,
    odometerPhotoUrl: "/car-odometer-45395km.jpg",
    odometerPhotoTakenBy: "Peter Novák",
    odometerPhotoTakenAt: "2024-01-15T12:30:00Z",
    ocrOriginalValue: 45398,
    ocrCorrectedValue: 45395,
    templateName: "Šablóna: Služobná cesta",
    type: "business",
    description: "Stretnutie s klientom",
    source: "gps_auto",
    locked: true,
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-01-15T12:30:00Z",
  },
  {
    id: "2",
    vehicleId: "2",
    driverId: "2",
    startLocation: "Bratislava, Petržalka",
    endLocation: "Trnava, Centrum",
    distanceKm: 55,
    startTime: "2024-01-16T09:00:00Z",
    endTime: "2024-01-16T10:15:00Z",
    type: "business",
    description: "Dodávka tovaru",
    source: "manual",
    locked: false,
    createdAt: "2024-01-16T09:00:00Z",
    updatedAt: "2024-01-16T10:15:00Z",
  },
  {
    id: "3",
    vehicleId: "1",
    driverId: "1",
    startLocation: "Bratislava, Hlavná 1",
    endLocation: "Bratislava, Ružinov",
    distanceKm: 15,
    startTime: "2024-01-17T14:00:00Z",
    endTime: "2024-01-17T14:30:00Z",
    type: "private",
    description: "Súkromná cesta",
    source: "gps_auto",
    locked: false,
    createdAt: "2024-01-17T14:00:00Z",
    updatedAt: "2024-01-17T14:30:00Z",
  },
]

// Mock Partner Settings
export const MOCK_PARTNER_SETTINGS: PartnerSettings[] = [
  {
    id: "1",
    userId: "1",
    isPartner: true,
    companyIco: "12345678",
    companyName: "Demo s.r.o.",
    bankAccount: "SK1234567890123456789012",
    rewardType: "commission",
    referralCode: "ADMIN2024",
    gdprConsent: true,
  },
  {
    id: "2",
    userId: "3",
    isPartner: true,
    companyIco: "98765432",
    companyName: "Účtovníctvo Plus s.r.o.",
    bankAccount: "SK9876543210987654321098",
    rewardType: "commission",
    referralCode: "UCTOVNIK2024",
    gdprConsent: true,
  },
]

// Mock Affiliate Stats
export const MOCK_AFFILIATE_STATS: Record<string, AffiliateStats> = {
  "1": {
    totalReferrals: 12,
    payingCustomers: 8,
    totalCommission: 450,
    bonusMonths: 0,
    pendingCommission: 120,
    paidCommission: 330,
    usedBonusMonths: 0,
  },
  "2": {
    totalReferrals: 3,
    payingCustomers: 1,
    totalCommission: 0,
    bonusMonths: 3,
    pendingCommission: 0,
    paidCommission: 0,
    usedBonusMonths: 1,
  },
  "3": {
    totalReferrals: 25,
    payingCustomers: 18,
    totalCommission: 850,
    bonusMonths: 0,
    pendingCommission: 200,
    paidCommission: 650,
    usedBonusMonths: 0,
  },
}

// Mock Affiliate Referrals
export const MOCK_AFFILIATE_REFERRALS: AffiliateReferral[] = [
  {
    id: "1",
    referralCode: "ADMIN2024",
    referredEmail: "klient1@example.com",
    referredUserId: "ref1",
    status: "active",
    signupDate: "2024-01-10T10:00:00Z",
    activationDate: "2024-01-15T10:00:00Z",
    commissionAmount: 15,
    bonusMonths: 0,
  },
  {
    id: "2",
    referralCode: "ADMIN2024",
    referredEmail: "klient2@example.com",
    referredUserId: "ref2",
    status: "active",
    signupDate: "2024-01-20T10:00:00Z",
    activationDate: "2024-01-22T10:00:00Z",
    commissionAmount: 15,
    bonusMonths: 0,
  },
  {
    id: "3",
    referralCode: "ADMIN2024",
    referredEmail: "klient3@example.com",
    status: "pending",
    signupDate: "2024-02-01T10:00:00Z",
    commissionAmount: 0,
    bonusMonths: 0,
  },
]

// Mock Affiliate History
export const MOCK_AFFILIATE_HISTORY: AffiliateHistory[] = [
  {
    id: "1",
    date: "2024-01-15T10:00:00Z",
    action: "activation",
    clientEmail: "klient1@example.com",
    amount: 15,
    description: "Klient aktivoval predplatné",
  },
  {
    id: "2",
    date: "2024-01-22T10:00:00Z",
    action: "activation",
    clientEmail: "klient2@example.com",
    amount: 15,
    description: "Klient aktivoval predplatné",
  },
  {
    id: "3",
    date: "2024-02-01T10:00:00Z",
    action: "signup",
    clientEmail: "klient3@example.com",
    description: "Nová registrácia cez váš link",
  },
  {
    id: "4",
    date: "2024-02-15T10:00:00Z",
    action: "renewal",
    clientEmail: "klient1@example.com",
    amount: 15,
    description: "Predplatné predĺžené",
  },
]

// Mock Trip Change Logs
export const MOCK_TRIP_CHANGE_LOGS: TripChangeLog[] = [
  {
    id: "1",
    tripId: "1",
    userId: "1",
    userName: "Admin",
    changedAt: "2024-01-15T13:00:00Z",
    field: "type",
    oldValue: "unknown",
    newValue: "business",
    description: "Zmenil typ jazdy z neznáma na služobná",
  },
  {
    id: "2",
    tripId: "1",
    userId: "1",
    userName: "Admin",
    changedAt: "2024-01-15T13:05:00Z",
    field: "distanceKm",
    oldValue: "398",
    newValue: "395",
    description: "Opravil vzdialenosť po manuálnej kontrole",
  },
  {
    id: "3",
    tripId: "1",
    userId: "3",
    userName: "Účtovník",
    changedAt: "2024-01-15T14:00:00Z",
    field: "description",
    oldValue: "Stretnutie",
    newValue: "Stretnutie s klientom",
    description: "Upravil účel jazdy",
  },
  {
    id: "4",
    tripId: "1",
    userId: "3",
    userName: "Účtovník",
    changedAt: "2024-01-15T15:00:00Z",
    field: "locked",
    oldValue: "false",
    newValue: "true",
    description: "Uzamkol jazdu",
  },
]

// Mock Refuelings
export const MOCK_REFUELINGS: Refueling[] = [
  {
    id: "1",
    vehicleId: "1",
    driverId: "1",
    date: "2024-01-10T10:30:00Z",
    liters: 45.5,
    pricePerLiter: 1.52,
    totalPrice: 69.16,
    fuelType: "diesel",
    odometerKm: 45200,
    location: "Shell, Bratislava",
    invoiceNumber: "INV-2024-001",
    notes: "Plná nádrž",
  },
  {
    id: "2",
    vehicleId: "1",
    driverId: "1",
    date: "2024-01-20T15:45:00Z",
    liters: 42.0,
    pricePerLiter: 1.54,
    totalPrice: 64.68,
    fuelType: "diesel",
    odometerKm: 45650,
    location: "OMV, Košice",
    invoiceNumber: "INV-2024-002",
  },
  {
    id: "3",
    vehicleId: "2",
    driverId: "2",
    date: "2024-01-15T09:00:00Z",
    liters: 50.0,
    pricePerLiter: 1.65,
    totalPrice: 82.5,
    fuelType: "petrol",
    odometerKm: 52100,
    location: "MOL, Trnava",
  },
]

// Mock Maintenance Records
export const MOCK_MAINTENANCE_RECORDS: MaintenanceRecord[] = [
  {
    id: "1",
    vehicleId: "1",
    type: "service",
    date: "2024-01-05T10:00:00Z",
    odometerKm: 45000,
    description: "Pravidelný servis - výmena oleja a filtrov",
    cost: 120.5,
    serviceProvider: "Autoservis Plus s.r.o.",
    invoiceNumber: "SRV-2024-001",
    notes: "Odporúčaná výmena brzdových platničiek pri ďalšom servise",
  },
  {
    id: "2",
    vehicleId: "1",
    type: "inspection",
    date: "2023-12-15T14:00:00Z",
    odometerKm: 44800,
    description: "STK kontrola",
    cost: 35.0,
    serviceProvider: "STK Centrum Bratislava",
    invoiceNumber: "STK-2023-456",
  },
  {
    id: "3",
    vehicleId: "2",
    type: "repair",
    date: "2024-01-12T11:00:00Z",
    odometerKm: 52050,
    description: "Oprava klimatizácie",
    cost: 285.0,
    serviceProvider: "Auto Klima Service",
    invoiceNumber: "REP-2024-089",
  },
]

// Mock Scheduled Maintenance
export const MOCK_SCHEDULED_MAINTENANCE: ScheduledMaintenance[] = [
  {
    id: "1",
    vehicleId: "1",
    type: "inspection",
    dueDate: "2024-12-15",
    dueOdometerKm: 60000,
    description: "Pravidelná technická kontrola (STK)",
    status: "pending",
    reminderDays: 30,
  },
  {
    id: "2",
    vehicleId: "1",
    type: "emissions",
    dueDate: "2024-12-15",
    description: "Emisná kontrola",
    status: "pending",
    reminderDays: 30,
  },
  {
    id: "3",
    vehicleId: "1",
    type: "oil_change",
    dueDate: "2024-06-01",
    dueOdometerKm: 50000,
    description: "Výmena motorového oleja",
    status: "pending",
    reminderDays: 14,
  },
  {
    id: "4",
    vehicleId: "2",
    type: "tire_change",
    dueDate: "2024-11-01",
    description: "Výmena letných pneumatík za zimné",
    status: "pending",
    reminderDays: 7,
  },
]

// Mock Odometer Readings
export const MOCK_ODOMETER_READINGS: OdometerReading[] = [
  {
    id: "1",
    vehicleId: "1",
    date: "2024-01-01T00:00:00Z",
    odometerKm: 45000,
    source: "manual",
    recordedBy: "Admin",
  },
  {
    id: "2",
    vehicleId: "1",
    date: "2024-01-15T12:30:00Z",
    odometerKm: 45395,
    photoUrl: "/car-odometer-45395km.jpg",
    source: "photo",
    recordedBy: "Peter Novák",
  },
  {
    id: "3",
    vehicleId: "1",
    date: "2024-01-20T18:00:00Z",
    odometerKm: 45650,
    source: "gps",
  },
  {
    id: "4",
    vehicleId: "2",
    date: "2024-01-01T00:00:00Z",
    odometerKm: 52000,
    source: "manual",
    recordedBy: "Admin",
  },
]

// Mock Places
export const MOCK_PLACES: Place[] = [
  {
    id: "1",
    name: "Demo s.r.o. - Sídlo",
    type: "headquarters",
    address: {
      street: "Hlavná",
      number: "1",
      city: "Bratislava",
      postalCode: "811 01",
      country: "Slovensko",
    },
    latitude: 48.1486,
    longitude: 17.1077,
    isCompanyLocation: true,
    notes: "Hlavné sídlo firmy",
    tripPurposes: ["Pracovná cesta", "Obchodná schôdzka", "Administratíva"],
    defaultPurposeIndex: 0,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Klient ABC s.r.o.",
    type: "client",
    address: {
      street: "Obchodná",
      number: "25",
      city: "Košice",
      postalCode: "040 01",
      country: "Slovensko",
    },
    latitude: 48.7164,
    longitude: 21.2611,
    notes: "Hlavný zákazník",
    tripPurposes: ["Dodanie tovaru", "Servisná prehliadka", "Obchodné rokovanie"],
    defaultPurposeIndex: 0,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    name: "Sklad",
    type: "own_place",
    address: {
      street: "Priemyselná",
      number: "10",
      city: "Žilina",
      postalCode: "010 01",
      country: "Slovensko",
    },
    latitude: 49.2208,
    longitude: 18.7398,
    isCompanyLocation: true,
    notes: "Centrálny sklad",
    tripPurposes: ["Preberanie tovaru", "Inventúra", "Nakladanie"],
    defaultPurposeIndex: 0,
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Domov - Peter Novák",
    type: "own_place",
    address: {
      street: "Ružová",
      number: "8",
      city: "Bratislava",
      postalCode: "821 09",
      country: "Slovensko",
    },
    latitude: 48.1562,
    longitude: 17.1189,
    isCompanyLocation: false,
    tripPurposes: ["Cesta domov", "Návrat z práce"],
    defaultPurposeIndex: 0,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Klient XYZ Ltd.",
    type: "client",
    address: {
      street: "Továrna",
      number: "22",
      city: "Žilina",
      postalCode: "010 01",
      country: "Slovensko",
    },
    latitude: 49.2235,
    longitude: 18.739,
    isCompanyLocation: false,
    notes: "Týždenné dodávky",
    tripPurposes: ["Dodanie materiálu", "Stretnutie s klientom", "Obchodná cesta"],
    defaultPurposeIndex: 0,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    name: "Pobočka Nitra",
    type: "own_place",
    address: {
      street: "Štefánikova",
      number: "45",
      city: "Nitra",
      postalCode: "949 01",
      country: "Slovensko",
    },
    latitude: 48.3088,
    longitude: 18.0877,
    isCompanyLocation: true,
    notes: "Obchodná pobočka pre región Nitra",
    tripPurposes: ["Obchodné rokovanie", "Servisná prehliadka", "Dodanie tovaru"],
    defaultPurposeIndex: 0,
    createdAt: "2024-01-10T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
]

// Mock Trip Templates
export const MOCK_TRIP_TEMPLATES: TripTemplate[] = [
  {
    id: "1",
    name: "Domov → Firma (ranná cesta)",
    vehicleId: "1",
    fromPlaceId: "4",
    toPlaceId: "1",
    distanceKm: 12,
    defaultType: "business",
    defaultDescription: "Cesta do práce",
    enabledForMobileAuto: true,
    priority: 1,
    kmTolerance: 3,
    timeFilterEnabled: true,
    timeFilterStart: "07:00",
    timeFilterEnd: "09:00",
    workdaysOnly: true,
    isRecurring: true,
    isAllDayTrip: false,
    isOneWay: false,
    returnTrip: {
      enabled: true,
      afterBreakMinutes: 480, // 8 hours work day
      timeTolerance: 30,
    },
    waypoints: [],
    allowOnHolidays: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Firma → Domov (večerná cesta)",
    vehicleId: "1",
    fromPlaceId: "1",
    toPlaceId: "4",
    distanceKm: 12,
    defaultType: "business",
    defaultDescription: "Cesta z práce",
    enabledForMobileAuto: true,
    priority: 2,
    kmTolerance: 3,
    timeFilterEnabled: true,
    timeFilterStart: "15:00",
    timeFilterEnd: "18:00",
    workdaysOnly: true,
    isRecurring: true,
    isAllDayTrip: false,
    isOneWay: true,
    returnTrip: {
      enabled: true,
      afterBreakMinutes: 60,
      timeTolerance: 15,
    },
    waypoints: [],
    allowOnHolidays: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Firma → Klient ABC",
    fromPlaceId: "1",
    toPlaceId: "2",
    distanceKm: 395,
    defaultType: "business",
    defaultDescription: "Služobná cesta - stretnutie s klientom",
    enabledForMobileAuto: true,
    priority: 3,
    kmTolerance: 10,
    timeFilterEnabled: false,
    workdaysOnly: false,
    isRecurring: false,
    isAllDayTrip: true, // Full day trip
    isOneWay: false,
    returnTrip: {
      enabled: true,
      exactTime: "16:00",
      timeTolerance: 60,
    },
    waypoints: [
      {
        id: "w1",
        placeId: "3",
        placeName: "Sklad - Trnava",
        order: 0,
        isFixed: true,
      },
    ],
    allowOnHolidays: true, // Can be executed on holidays
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Firma → Sklad Trnava",
    fromPlaceId: "1",
    toPlaceId: "3",
    distanceKm: 55,
    defaultType: "business",
    defaultDescription: "Doprava materiálu",
    enabledForMobileAuto: true,
    priority: 4,
    kmTolerance: 5,
    timeFilterEnabled: false,
    workdaysOnly: true,
    isRecurring: false,
    isAllDayTrip: false,
    isOneWay: false,
    returnTrip: {
      enabled: true,
      afterBreakMinutes: 60,
      timeTolerance: 15,
    },
    waypoints: [],
    allowOnHolidays: false,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]

// Mock Internal Reports
export const MOCK_INTERNAL_REPORTS: InternalReport[] = [
  {
    id: "1",
    name: "Mesačný report - Január 2024",
    type: "monthly",
    period: "2024-01",
    dateFrom: "2024-01-01",
    dateTo: "2024-01-31",
    totalTrips: 45,
    totalKm: 2770,
    businessKm: 2450,
    privateKm: 320,
    totalCost: 1250.5,
    createdAt: "2024-02-01T10:00:00Z",
    createdBy: "Admin User",
  },
  {
    id: "2",
    name: "Q1 2024 - Všetky vozidlá",
    type: "quarterly",
    period: "Q1 2024",
    dateFrom: "2024-01-01",
    dateTo: "2024-03-31",
    totalTrips: 132,
    totalKm: 7500,
    businessKm: 6480,
    privateKm: 1020,
    totalCost: 3680.75,
    createdAt: "2024-04-05T10:00:00Z",
    createdBy: "Admin User",
  },
]

// Mock Export Templates
export const MOCK_EXPORT_TEMPLATES: ExportTemplate[] = [
  {
    id: "1",
    name: "Daňový export jázd",
    format: "excel",
    type: "trips",
    fields: ["date", "vehicle", "driver", "from", "to", "km", "type", "purpose"],
    isDefault: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    name: "DPH výkaz CSV",
    format: "csv",
    type: "vat",
    fields: ["period", "vehicle", "businessKm", "privateKm", "percentage"],
    isDefault: false,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "3",
    name: "Nákladový report PDF",
    format: "pdf",
    type: "costs",
    fields: ["date", "vehicle", "type", "amount", "description"],
    isDefault: false,
    createdAt: "2024-02-10T10:00:00Z",
  },
]

// Mock VAT Reports
export const MOCK_VAT_REPORTS: VatReport[] = [
  {
    id: "1",
    period: "2024-01",
    vehicleId: "1",
    status: "locked",
    totalKm: 2770,
    businessKm: 2450,
    privateKm: 320,
    startOdometer: 45000,
    endOdometer: 47770,
    tripCount: 45,
    fuelCosts: 450.5,
    maintenanceCosts: 120.5,
    tollCosts: 35.0,
    generatedAt: "2024-01-31T14:00:00Z",
    generatedBy: "Admin",
    lockedAt: "2024-02-05T09:30:00Z",
    lockedBy: "Admin",
    createdAt: "2024-01-31T10:00:00Z",
    updatedAt: "2024-02-05T09:30:00Z",
  },
  {
    id: "2",
    period: "2024-02",
    vehicleId: "1",
    status: "generated",
    totalKm: 2100,
    businessKm: 1890,
    privateKm: 210,
    startOdometer: 47770,
    endOdometer: 49870,
    tripCount: 38,
    fuelCosts: 380.0,
    maintenanceCosts: 0,
    tollCosts: 28.0,
    generatedAt: "2024-02-29T14:00:00Z",
    generatedBy: "Admin",
    createdAt: "2024-02-29T10:00:00Z",
    updatedAt: "2024-02-29T14:00:00Z",
  },
  {
    id: "3",
    period: "2024-Q1",
    status: "draft",
    totalKm: 7500,
    businessKm: 6480,
    privateKm: 1020,
    startOdometer: 45000,
    endOdometer: 52500,
    tripCount: 132,
    fuelCosts: 1250.5,
    maintenanceCosts: 320.0,
    tollCosts: 98.0,
    createdAt: "2024-04-01T10:00:00Z",
    updatedAt: "2024-04-01T10:00:00Z",
  },
]

// Mock Company Settings
export const MOCK_COMPANY_SETTINGS: CompanySettings = {
  id: "1",
  companyId: "1",
  vatPayerType: "monthly",
  autoGenerateVatReports: true,
  defaultVehicleVatRegime: "50_mixed",
  mobileAutoGenerateTrips: true,
  mobileRequiresConfirmation: false,
  globalKmTolerance: 5,
  autofillDefaultTripPurpose: true,
  calendarSync: {
    enabled: false,
    provider: "google",
    syncType: "all",
    autoSync: false,
    syncIntervalMinutes: 60,
  },
  notifications: [
    {
      type: "vat_deadline_approaching",
      enabled: true,
      channels: ["email", "in_app"],
      advanceDays: 7,
    },
    {
      type: "missing_odometer_photo",
      enabled: true,
      channels: ["email", "push", "in_app"],
      advanceDays: 3,
    },
    {
      type: "km_mismatch",
      enabled: true,
      channels: ["in_app"],
      kmTolerance: 10,
    },
    {
      type: "fuel_costs_anomaly",
      enabled: false,
      channels: ["email"],
      fuelLiterTolerance: 5,
    },
    {
      type: "private_trip_on_business_vehicle",
      enabled: true,
      channels: ["email", "in_app"],
    },
    {
      type: "insurance_expiry_approaching",
      enabled: true,
      channels: ["email", "push", "in_app"],
      advanceDays: 30,
    },
  ],
}

// Mock User Roles
export const MOCK_USER_ROLES: UserRole[] = [
  {
    id: "1",
    userId: "1",
    name: "Admin",
    email: "admin@knihajazd.sk",
    role: "admin",
    active: true,
    createdAt: "2024-01-01T00:00:00Z",
    lastLogin: "2024-01-20T10:30:00Z",
  },
  {
    id: "2",
    userId: "2",
    name: "Peter Novák",
    email: "vodic@knihajazd.sk",
    role: "driver",
    active: true,
    createdAt: "2024-01-05T00:00:00Z",
    lastLogin: "2024-01-19T15:20:00Z",
  },
  {
    id: "3",
    userId: "3",
    name: "Účtovník",
    email: "uctovnik@knihajazd.sk",
    role: "accountant",
    active: true,
    createdAt: "2024-01-03T00:00:00Z",
    lastLogin: "2024-01-20T08:15:00Z",
  },
]

// Mock Vehicle Documents
export const MOCK_VEHICLE_DOCUMENTS: VehicleDocument[] = [
  {
    id: "doc-1",
    vehicleId: "1",
    type: "registration",
    name: "Technický preukaz BA123CD",
    fileUrl: "/documents/tech-preukaz-ba123cd.pdf",
    uploadedAt: "2024-01-15T10:00:00Z",
    uploadedBy: "Admin User",
    notes: "Platný do 2025",
  },
  {
    id: "doc-2",
    vehicleId: "1",
    type: "insurance",
    name: "Poistná zmluva Allianz",
    fileUrl: "/documents/insurance-ba123cd.pdf",
    uploadedAt: "2024-01-20T14:30:00Z",
    uploadedBy: "Admin User",
  },
  {
    id: "doc-3",
    vehicleId: "1",
    type: "service",
    name: "Servisný protokol 01/2024",
    fileUrl: "/documents/service-ba123cd-01-2024.pdf",
    uploadedAt: "2024-01-25T09:15:00Z",
    uploadedBy: "Admin User",
    notes: "Výmena oleja a filtrov",
  },
  {
    id: "doc-4",
    vehicleId: "2",
    type: "registration",
    name: "Technický preukaz BA456EF",
    fileUrl: "/documents/tech-preukaz-ba456ef.pdf",
    uploadedAt: "2024-02-10T11:20:00Z",
    uploadedBy: "Admin User",
  },
]

// Mock Holidays
export const MOCK_HOLIDAYS: Holiday[] = [
  {
    id: "1",
    date: "2025-01-01",
    name: "Deň vzniku Slovenskej republiky",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    date: "2025-01-06",
    name: "Zjavenie Pána (Traja králi)",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "3",
    date: "2025-04-18",
    name: "Veľký piatok",
    type: "public",
    country: "Slovensko",
    recurring: false,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "4",
    date: "2025-04-21",
    name: "Veľkonočný pondelok",
    type: "public",
    country: "Slovensko",
    recurring: false,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "5",
    date: "2025-05-01",
    name: "Sviatok práce",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "6",
    date: "2025-05-08",
    name: "Deň víťazstva nad fašizmom",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "7",
    date: "2025-07-05",
    name: "Sviatok svätého Cyrila a Metoda",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "8",
    date: "2025-08-29",
    name: "Výročie SNP",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "9",
    date: "2025-09-01",
    name: "Deň Ústavy Slovenskej republiky",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "10",
    date: "2025-09-15",
    name: "Sedembolestná Panna Mária",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "11",
    date: "2025-11-01",
    name: "Sviatok všetkých svätých",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "12",
    date: "2025-11-17",
    name: "Deň boja za slobodu a demokraciu",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "13",
    date: "2025-12-24",
    name: "Štedrý deň",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "14",
    date: "2025-12-25",
    name: "Prvý sviatok vianočný",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "15",
    date: "2025-12-26",
    name: "Druhý sviatok vianočný",
    type: "public",
    country: "Slovensko",
    recurring: true,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "16",
    date: "2025-07-01",
    name: "Celozávodná dovolenka",
    type: "company",
    country: "Slovensko",
    recurring: false,
    createdBy: "Admin",
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
]

// Mock Planned Trips
export const MOCK_PLANNED_TRIPS: PlannedTrip[] = [
  {
    id: "pt-1",
    vehicleId: "1",
    driverId: "1",
    templateId: "1",
    plannedDate: "2025-01-27",
    plannedTimeFrom: "08:00",
    plannedTimeTo: "08:30",
    fromPlaceId: "4",
    toPlaceId: "1",
    distanceKm: 12,
    type: "business",
    description: "Ranná cesta do práce",
    status: "planned",
    isRecurring: true,
    recurrencePattern: {
      type: "workdays",
      startDate: "2025-01-27",
      endDate: "2025-12-31",
      timeTolerance: 15,
    },
    waypoints: [],
    isOneWay: false,
    returnTrip: {
      enabled: true,
      afterBreakMinutes: 480,
      timeTolerance: 30,
    },
    allowOnHolidays: false,
    createdAt: "2025-01-20T00:00:00Z",
    createdBy: "user-1",
    updatedAt: "2025-01-20T00:00:00Z",
  },
  {
    id: "pt-2",
    vehicleId: "1",
    templateId: "3",
    plannedDate: "2025-01-28",
    plannedTimeFrom: "09:00",
    plannedTimeTo: "17:00",
    fromPlaceId: "1",
    toPlaceId: "2",
    distanceKm: 395,
    type: "business",
    description: "Služobná cesta k klientovi ABC",
    status: "planned",
    isRecurring: false,
    waypoints: [
      {
        id: "w1",
        placeId: "3",
        placeName: "Sklad",
        order: 0,
        isFixed: true,
      },
    ],
    isOneWay: false,
    returnTrip: {
      enabled: true,
      exactTime: "16:00",
      timeTolerance: 60,
    },
    allowOnHolidays: true,
    createdAt: "2025-01-22T00:00:00Z",
    createdBy: "user-1",
    updatedAt: "2025-01-22T00:00:00Z",
  },
]
